version: "2"

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=postgres

  pgadmin:
    container_name: pgadmin4
    image: fenglc/pgadmin4
    ports:
      - 5050:5050